spring.jpa.generate-ddl=true
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://dpg-d0c5ci15pdvs73d983lg-a.oregon-postgres.render.com:5432/db_blogpessoal_2qmz
spring.datasource.username=db_blogpessoal_2qmz_user
spring.datasource.password=R88OQ9Rx64LA7wRXm1frMQMObLEyakRo

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.jakarta.persistence.sharedCache.mode=ENABLE_SELECTIVE

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Brazil/East